SELECT F.HACKER_ID, F.NAME, SUM(F.SCORE)
FROM (
    SELECT S.hacker_id, H.name, MAX(S.SCORE) AS SCORE
    FROM Submissions AS S INNER JOIN Hackers AS H
        USING (HACKER_ID)
    GROUP BY S.HACKER_ID, H.name, S.CHALLENGE_ID
) AS F
GROUP BY F.HACKER_ID, F.NAME
HAVING SUM(F.SCORE) != 0
ORDER BY SUM(F.SCORE) DESC, HACKER_ID ASC;
